/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthPagesImport } from './routes/_authPages'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthPagesSignUpImport } from './routes/_authPages/sign-up'
import { Route as AuthPagesSignInImport } from './routes/_authPages/sign-in'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthPagesRoute = AuthPagesImport.update({
  id: '/_authPages',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthPagesSignUpRoute = AuthPagesSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthPagesRoute,
} as any)

const AuthPagesSignInRoute = AuthPagesSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthPagesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authPages': {
      id: '/_authPages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthPagesImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authPages/sign-in': {
      id: '/_authPages/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthPagesSignInImport
      parentRoute: typeof AuthPagesImport
    }
    '/_authPages/sign-up': {
      id: '/_authPages/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthPagesSignUpImport
      parentRoute: typeof AuthPagesImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthPagesRouteChildren {
  AuthPagesSignInRoute: typeof AuthPagesSignInRoute
  AuthPagesSignUpRoute: typeof AuthPagesSignUpRoute
}

const AuthPagesRouteChildren: AuthPagesRouteChildren = {
  AuthPagesSignInRoute: AuthPagesSignInRoute,
  AuthPagesSignUpRoute: AuthPagesSignUpRoute,
}

const AuthPagesRouteWithChildren = AuthPagesRoute._addFileChildren(
  AuthPagesRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof AuthPagesSignInRoute
  '/sign-up': typeof AuthPagesSignUpRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthPagesRouteWithChildren
  '/sign-in': typeof AuthPagesSignInRoute
  '/sign-up': typeof AuthPagesSignUpRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authPages': typeof AuthPagesRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authPages/sign-in': typeof AuthPagesSignInRoute
  '/_authPages/sign-up': typeof AuthPagesSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/sign-in' | '/sign-up' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/sign-in' | '/sign-up' | '/'
  id:
    | '__root__'
    | '/_authPages'
    | '/_authenticated'
    | '/_authPages/sign-in'
    | '/_authPages/sign-up'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthPagesRoute: typeof AuthPagesRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthPagesRoute: AuthPagesRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authPages",
        "/_authenticated"
      ]
    },
    "/_authPages": {
      "filePath": "_authPages.tsx",
      "children": [
        "/_authPages/sign-in",
        "/_authPages/sign-up"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/"
      ]
    },
    "/_authPages/sign-in": {
      "filePath": "_authPages/sign-in.tsx",
      "parent": "/_authPages"
    },
    "/_authPages/sign-up": {
      "filePath": "_authPages/sign-up.tsx",
      "parent": "/_authPages"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
